const MESSAGE = {
  EMAIL_INVALID: 'Email không hợp lệ',
  EMAIL_REQUIRED: 'Thiếu email',
  PASSWORD_INVALID: 'Mật khẩu không hợp lệ',
  PASSWORD_REQUIRED: 'Thiếu mật khẩu',
  NEWPASSWORD_INVALID: 'Mật khẩu mới không hợp lệ',
  NEWPASSWORD_REQUIRED: 'Thiếu mật khẩu mới',
  NEWPASSWORD_NOT_MATCH_CURRENTPASSWORD: 'Mật khẩu mới không trùng với mật khẩu cũ',
  FULLNAME_INVALID: 'Tên người dùng không hợp lệ',
  FULLNAME_REQUIRED: 'Thiếu tên người dùng',
  GENDER_INVALID: 'Giới tính không hợp lệ',
  GENDER_REQUIRED: 'Thiếu giới tính',
  PHONE_INVALID: 'Số điện thoại không hợp lệ',
  PHONE_REQUIRED: 'Thiếu số điện thoại',
  AVATAR_INVALID: 'Ảnh đại diện không hợp lệ',
  ROLE_INVALID: 'Vai trò không hợp lệ',
  ROLE_REQUIRED: 'Thiếu vai trò',
  IS_NOT_AUTH: 'Chưa được xác thực',
  IS_NOT_AUTH_ADMIN: 'Không phải quản trị viên',
  IS_NOT_AUTH_SELLER: 'Không phải người bán',
  IS_NOT_AUTH_BUYER: 'Không phải người mua',
  INFORMATION_INVALID: 'Thông tin không hợp lệ',
  EMAIL_BE_USED: 'Email đã được sử dụng',
  REGISTER_SUCCESS: 'Đăng ký thành công',
  LOGOUT_SUCCESS: 'Đăng xuất thành công',
  LOGIN_SUCCESS: 'Đăng nhập thành công',
  CREATE_SHOP_SUCCESS: 'Tạo gian hàng thành công',
  CREATE_PRODUCT_SUCCESS: 'Tạo thêm sản phẩm thành công',
  CHANGE_PASSWORD_SUCCESS: 'Đổi mật khẩu thành công',
  EMAIL_RESET_PASSWORD_BE_SEND: 'Email yêu cầu đổi mật khẩu được gửi',
  SUBJECT_FORGET_PASSWORD: 'THAY ĐỔI MẬT KHẨU',
  TOKEN_INVALID: 'Mã code không hợp lệ',
  TOKEN_REQUIRED: 'Thiếu mã code',
  UPDATE_PROFILE_SUCCESS: 'Cập nhật hồ sơ cá nhân thành công',
  NOT_ALLOW: 'không đúng quyền hạn',
  PAGE_NOK: 'số trang không hợp lệ',
  SIZE_NOK: 'kích thước trang không hợp lệ',
  ID_NOK: 'id không hợp lệ',
  GET_LIST_USER_SUCCESS: 'lấy danh sách người dùng thành công',
  GET_LIST_SHOP_SUCCESS: 'lấy danh sách gian hàng thành công',
  GET_LIST_PRODUCT_SUCCESS: 'lấy danh sách sản phẩm thành công',
  MAX_PRICE_NOK: 'giá tối đa không hợp lệ',
  MIN_PRICE_NOK: 'giá tối thiểu không hợp lệ',
  PRICE_NOK: 'giá không hợp lệ',
  NAME_NOK: 'tên không hợp lệ',
  SEARCH_PRODUCT_SUCCESS: 'tìm kiếm sản phẩm thành công',
  QUANTITY_NOK: 'số lượng không hợp lệ',
  IMAGE_ARRAY: 'mảng ảnh không hợp lệ',
  STATUS_ORDER_NOK: 'trạng thái đơn hàng không hợp lệ',
  PAYMENT_NOK: 'trạng thái thanh toán không hợp lệ',
  NAME_SHOP_REQUIRED: 'thiếu tên gian hàng',
  ADDRESS_SHOP_REQUIRED: 'thiếu địa chỉ gian hàng',
  LOGO_SHOP_REQUIRED: 'thiếu logo gian hàng',
  NOT_OWN_SHOP: 'Gian hàng không thuộc quản lý',
  IMAGE_INVALID: 'Ảnh không hợp lệ',
}

module.exports = MESSAGE;